name: Coveralls

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: true
    - uses: cardinalby/export-env-action@v2
      with:
        envFile: 'github.env'
    - name: Build and Test ACadSharp.Pdf
      working-directory: src
      run: |
          git submodule update --force --recursive --init --remote
          dotnet restore
          dotnet build --no-restore
          dotnet test -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=lcov --no-build --verbosity normal ACadSharp.Pdf.Tests/
    - name: Build and Test Submodules
      working-directory: src/ACadSharp/src
      run: |
          git submodule update --force --recursive --init --remote
          dotnet restore
          dotnet build --no-restore
          dotnet test -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=lcov --verbosity normal ACadSharp.Tests/
          dotnet test -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=lcov --verbosity normal CSUtilities/CSUtilities.Tests/
          dotnet test -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=lcov --verbosity normal CSUtilities/CSMath.Tests/
    - name: Coveralls action
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ github.token }}
        files: src/ACadSharp.Pdf.Tests/TestResults/coverage.info src/ACadSharp/src/ACadSharp.Tests/TestResults/coverage.info src/ACadSharp/src/CSUtilities/CSUtilities.Tests/TestResults/coverage.info src/ACadSharp/src/CSUtilities/CSMath.Tests/TestResults/coverage.info 