name: Publish NuGet package

on:
 workflow_dispatch:
 release:
    branches: [ master ]

 # remove on merge
 pull_request:
    branches: [ master ]

jobs:
 build:
   runs-on: windows-latest
   steps:
   - uses: actions/checkout@v3
     with: 
       submodules: true
       fetch-depth: 0
   - name: Publish NuGet package
     working-directory: src
     run: |
         git submodule update --force --recursive --init --remote
         dotnet restore
         dotnet pack ./ACadSharp.pdf/ACadSharp.Pdf.csproj -c Release
         dotnet nuget push ./nupkg/ACadSharp.Pdf.*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json